#!/usr/bin/env python3

import sys

def next_ver(ver : str, fn) -> str:
    trio = list(map(int, ver.split('.')))
    trio = fn(trio)
    return '.'.join(map(str, trio))

def roll_patch(trio):
    trio[2] += 1
    return trio

def roll_minor(trio):
    trio[1] += 1
    trio[2] = 0
    return trio

def roll_major(trio):
    trio[0] += 1
    trio[1] = 0
    trio[2] = 0
    return trio

rollers = {
    "patch": roll_patch,
    "minor": roll_minor,
    "major": roll_major
}

if __name__ == '__main__':
    if (len(sys.argv) < 3):
        print("usage: roll.py <patch | minor | major> <version>")
        sys.exit(1)

    how = sys.argv[1]
    ver = sys.argv[2]
    roller = rollers[how]
    print(next_ver(ver, roller))
